/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lista05;

import static com.mycompany.lista05.Quadrante.PRIMEIRO;
import static com.mycompany.lista05.Quadrante.SEGUNDO;
import static com.mycompany.lista05.Quadrante.TERCEIRO;

/**
 *
 * @author user
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFEixoX = new javax.swing.JTextField();
        jTFEixoY = new javax.swing.JTextField();
        jBtnAvaliar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCBEixoX = new javax.swing.JCheckBox();
        jCBEixoY = new javax.swing.JCheckBox();
        jCBPrimeiroQuadrante = new javax.swing.JCheckBox();
        jCBSegundoQuadrante = new javax.swing.JCheckBox();
        jCBTerceiroQuadrante = new javax.swing.JCheckBox();
        jCBQuartoQuadrante = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eixo X:");

        jLabel2.setText("Eixo Y:");

        jTFEixoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEixoYActionPerformed(evt);
            }
        });

        jBtnAvaliar.setText("Avaliar");
        jBtnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAvaliarActionPerformed(evt);
            }
        });

        jLabel3.setText("Posição:");

        jCBEixoX.setText("EixoX");
        jCBEixoX.setEnabled(false);

        jCBEixoY.setText("EixoY");
        jCBEixoY.setEnabled(false);

        jCBPrimeiroQuadrante.setText("Primeiro Quadrante");
        jCBPrimeiroQuadrante.setEnabled(false);

        jCBSegundoQuadrante.setText("Segundo Quadrante");
        jCBSegundoQuadrante.setEnabled(false);

        jCBTerceiroQuadrante.setText("Terceiro Quadrante");
        jCBTerceiroQuadrante.setEnabled(false);

        jCBQuartoQuadrante.setText("Quarto Quadrante");
        jCBQuartoQuadrante.setEnabled(false);
        jCBQuartoQuadrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBQuartoQuadranteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTFEixoY, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTFEixoX)))
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAvaliar)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBEixoX)
                    .addComponent(jCBPrimeiroQuadrante)
                    .addComponent(jCBEixoY)
                    .addComponent(jCBSegundoQuadrante)
                    .addComponent(jCBTerceiroQuadrante)
                    .addComponent(jCBQuartoQuadrante))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTFEixoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFEixoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jBtnAvaliar)))
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBEixoX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBEixoY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBPrimeiroQuadrante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBSegundoQuadrante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBTerceiroQuadrante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBQuartoQuadrante)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFEixoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEixoYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEixoYActionPerformed

    private void jBtnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAvaliarActionPerformed
        int x = Integer.parseInt(jTFEixoX.getText());
        int y = Integer.parseInt(jTFEixoY.getText());
        
        Ponto ponto = new Ponto(x, y);
        
        jCBEixoX.setSelected(false);
        jCBEixoY.setSelected(false);
        jCBPrimeiroQuadrante.setSelected(false);
        jCBSegundoQuadrante.setSelected(false);
        jCBTerceiroQuadrante.setSelected(false);
        jCBQuartoQuadrante.setSelected(false);
        
        if(ponto.estaIncidindoSobreX()) jCBEixoX.setSelected(true);
        if(ponto.estaIncidindoSobreY()) jCBEixoY.setSelected(true);
        
        switch (ponto.indentificarQuadrante()){
            case PRIMEIRO:
                jCBPrimeiroQuadrante.setSelected(true);
            case SEGUNDO:
                jCBSegundoQuadrante.setSelected(true);
            case TERCEIRO:
                jCBTerceiroQuadrante.setSelected(true);
            case QUARTO:
                jCBQuartoQuadrante.setSelected(true);
        }
        buttonGroup1.add(jCBEixoX);
        buttonGroup1.add(jCBEixoY);
        buttonGroup1.add(jCBPrimeiroQuadrante);
        buttonGroup1.add(jCBSegundoQuadrante);
        buttonGroup1.add(jCBTerceiroQuadrante);
        buttonGroup1.add(jCBQuartoQuadrante);
        
        
        
    }//GEN-LAST:event_jBtnAvaliarActionPerformed

    private void jCBQuartoQuadranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBQuartoQuadranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBQuartoQuadranteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnAvaliar;
    private javax.swing.JCheckBox jCBEixoX;
    private javax.swing.JCheckBox jCBEixoY;
    private javax.swing.JCheckBox jCBPrimeiroQuadrante;
    private javax.swing.JCheckBox jCBQuartoQuadrante;
    private javax.swing.JCheckBox jCBSegundoQuadrante;
    private javax.swing.JCheckBox jCBTerceiroQuadrante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTFEixoX;
    private javax.swing.JTextField jTFEixoY;
    // End of variables declaration//GEN-END:variables

}
